tp/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tp.special;
using tp.ServiceReference1;

namespace tp.Controllers
{
    public partial class DetailController : Controller
    {
        //
        // GET: /Detail/
       
              [IsGuest]
        public ActionResult detail(Int64 number)
        {
         HttpContext.Response.AppendCookie(new HttpCookie("id_zaivki",number.ToString()));
      
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            zaivka z;
          client.get_full_zaivka_for_id(Auth.get_user(),number,out z);
           if (z == null)
               return RedirectToAction("Index", "Home");
            List<string> help_list ;
            client.get_users_for_zaivka(Auth.get_user(),number, out help_list);
           
           List<string> statuses;
                  List<string> help_list2;
           client.get_statuses(Auth.get_user(), out statuses);
           client.get_roles_for_zaivka(Auth.get_user(), number, out help_list2);
           ViewData["role_list"] = help_list2;
           ViewData["user_list"] = help_list;
            ViewData["statuses"] = statuses;
            bool is_owner,is_can;
                  //Принять Заявку!?
            if (z.new_logins.Exists(n=>n == Auth.get_user().login))
                ViewData["is_take"] = true;
            else
                ViewData["is_take"] = false;
            
                  //отмена передачи другому пользователю!?
            if ((z.current_login == Auth.get_user().login) && (z.new_logins.Count != 0))
                ViewData["is_back"] = true;
            else
                ViewData["is_back"] = false;
                  client.can_user_do_operation(Auth.get_user(),  "Передача ТП",z.id,out is_owner,out is_can);
                  //доступна ли операция перехода на следующее состояние
            if (is_can)
            {
                ViewData["CanSendToOther"] = true;
            }
            else
            {
                
                ViewData["CanSendToOther"] = false;
            }

            client.can_user_do_operation(Auth.get_user(), "Изменение статуса", z.id, out is_owner, out is_can);
            if (is_can==true)
            {
                ViewData["CanChangeStatus"] = true;
            }
            else
            {

                ViewData["CanChangeStatus"] = false;
            }
           
            object ob;
            userPartial.get_parameters(z, "detail", ViewData,TempData, out ob);
            client.Close();
                return View(z);
        }
             [IsGuest]
        public ActionResult send(string id_zaivki)
              {
          
                  Int64 number = Convert.ToInt64(id_zaivki);
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.go_next_state(number, Auth.get_user());
            client.Close();
            return RedirectToAction("detail", new { number=number});
        }
             [IsGuest]
        public ActionResult Change(FormCollection collection)
        {
                Int64 f =Convert.ToInt64(collection["id_zaivki"]);
            if (collection["Status"] != null)
            {
            
                ServiceReference1.PublisherServiceClient client = Auth.get_client();
                client.Change_status(Auth.get_user(),collection["status_value"],f);
                client.Close();
          
            }
            else
            
                if ((collection["send"] != null) && (collection["user_send"] != null))
                {
                    ServiceReference1.PublisherServiceClient client = Auth.get_client();
                    client.send_zaivka_to_user(f, collection["user_send"],null, Auth.get_user());
                    client.Close();
                  
                }
                    else
                    if (collection["take_back"] != null)
                    {
                        ServiceReference1.PublisherServiceClient client = Auth.get_client();
                        client.take_back_sending_zaivki(Auth.get_user(), f);
                        client.Close();
                       
                    }
                    else
                        if (collection["take_zaivka"] != null)
                    {
                        ServiceReference1.PublisherServiceClient client = Auth.get_client();
                        client.take_sending_zaivki(f, Auth.get_user());
                        client.Close();
                      


                    }
                        else

                            if ((collection["send_to_role"] != null)  && (collection["user_send_role"] != null))
                            {
                                ServiceReference1.PublisherServiceClient client = Auth.get_client();
                                client.send_zaivka_to_user(f, null, collection["user_send_role"], Auth.get_user());
                                client.Close();
                            }
                return RedirectToAction("detail", new { number = f });    

            
                
        }
        
    }
}

tp/Controllers/HistoryZaivokController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tp.Models;
using tp.special;

namespace tp.Controllers
{
    public class HistoryZaivokController : Controller
    {
        //
        // GET: /HistoryZaivok/

        public ActionResult Index(ServiceReference1.filter ff,int PageNum=0)
        {
             List<string> schems, users;
            Int64 count;
             ServiceReference1.PublisherServiceClient client = Auth.get_client();
             List<ServiceReference1.zaivka_history> list;
            
            client.get_schems(Auth.get_user(), out schems);
            client.get_users_list(Auth.get_user(), out users);
            client.getzaivkihistory(Auth.get_user(),ff, PageNum * 15, (PageNum + 1) * 15, out count, out list);
            findObject hh = new findObject { param = ff,schems=schems,users=users };
       
            ViewData["findobject"] = hh;

            vspomogatelnii.get(count, PageNum, 15, this.ViewData);


            return View(list);
        }
        public ActionResult find(FormCollection collection)
        {
            List<ServiceReference1.zaivka_history> list;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
        ServiceReference1.filter ff=    HomeController.filterparam(collection);
          

          return  RedirectToAction("Index",ff);
           
        }
        public ActionResult historysostoinii(Int64 id)
        {
            ServiceReference1.zaivka_history z_h;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.getzaivkahistory(Auth.get_user(),id,out z_h);
            ViewData["getstatuses"] = Url.Action("gethistorystatuses");
            ViewData["gethistorysended"] = Url.Action("gethistorysended");
            return View("DetailHistoryZaivki", z_h);
        }
        #region актуальная заявка
        public ActionResult getzaivkaactualhistory(Int64 id)
        {
            ServiceReference1.zaivka_history z_h;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.get_history_actualzaivki(Auth.get_user(), id, out z_h);
            ViewData["getstatuses"] = Url.Action("gethistoryactualstatuses");
            ViewData["gethistorysended"] = Url.Action("gethistoryactualsended");
            return View("DetailHistoryZaivki", z_h);
        }
        public JsonResult gethistoryactualsended(string id, string z_id)
        {
            ServiceReference1.zaivka_history z_h;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.get_history_actualzaivki(Auth.get_user(), Convert.ToInt64(z_id), out z_h);
            return Json(z_h.list.Where(m => m.ID == Convert.ToInt64(id)));
        }
        public JsonResult gethistoryactualstatuses(string id, string z_id)
        {
            ServiceReference1.zaivka_history z_h;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.get_history_actualzaivki(Auth.get_user(), Convert.ToInt64(z_id), out z_h);
            return Json(z_h.list.Where(m => m.ID == Convert.ToInt64(id)));
        }
        #endregion


        public JsonResult gethistorysended(string id, string z_id)
        {
            ServiceReference1.zaivka_history z_h;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.getzaivkahistory(Auth.get_user(), Convert.ToInt64(z_id), out z_h);
            return Json(z_h.list.Where(m => m.ID == Convert.ToInt64(id)));
        }
        public JsonResult gethistorystatuses(string id,string z_id)
        {
            ServiceReference1.zaivka_history z_h;
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            client.getzaivkahistory(Auth.get_user(),Convert.ToInt64(z_id), out z_h);
            return Json(z_h.list.Where(m => m.ID ==Convert.ToInt64( id)));
        }
    }
}

tp/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tp.ServiceReference1;
using tp.special;

namespace tp.Controllers
{
    public class NotificationController : Controller
    {
        //
        // GET: /Notification/

        public ActionResult Index()
        {
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            List<Notification_to_user> listtt;
            client.get_Notifications_user(Auth.get_user(), out listtt);
            TempData["notifications"] = listtt;
            return View();
        }

    }
}

tp/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using tp.special;
using tp.ServiceReference1;
using tp.Models;
namespace tp.Controllers
{
    public class StatisticController : Controller
    {
        //
        // GET: /Statistic/

        
        public ActionResult Index(string typestatistic="StatisticSotoinie")
        {

            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            if (!client.isboss(Auth.get_user().login))
            {
                ViewData["error_text"] = "нет прав!!!!";

                return View("userError");
            }
            switch (typestatistic)
            {
                case "StatisticSotoinie":

                   



                    ViewData["list"] = TempData["StatisticSotoinie"] as List<dicttime>;
                    List<shemsost> listsosoinii=   client.getschemssostoinie();
                List<string> users, schems;
                client.get_schems(Auth.get_user(), out schems);
                client.get_users_list(Auth.get_user(), out users);
            
                filter ff = (filter)TempData["filterparam"];
                ff = ff == null ? new filter() : ff;
                findObject obj = new findObject { param = ff, users = users, schems = schems, shem_sostoinii = listsosoinii };
                ViewData["filter"] = obj;
                client.Close();
                return View("StatisticSostoinie",obj);
                    break;
                default :
                    return View();
                    break;
            }
           
        }

        


        public ActionResult StatisticSotoinie(FormCollection collection)
        {
            ServiceReference1.PublisherServiceClient client = Auth.get_client();
            string schema = collection["schem_value"];
            string user = collection["user_value"];
            string sostoinie_value = collection["sost_value"];

           

            List<dicttime> list;
         error err=client.GetStatistics_sostoinie(Auth.get_user(),user, sostoinie_value, schema, out list);
         TempData["statistic"] = list;
         if (err.Is_error == true)
         {

             ViewData["error_text"] = err.error_text;
                 return View("userError");
         }
         else
         {
             TempData["StatisticSotoinie"] = list;
             return RedirectToAction("Index", new { typestatistic = "StatisticSotoinie" });
         }

        }

    }
}

tp/Views/Shared/_DetailUser.cshtml
<script>
    function getdetail(login) {
        $.ajax({
            type: "Post",
            url: '@Url.Action("getuser","Home")' + '?login='+login,
           
            cache: false,
            success: function (data) {

                $("#roles").empty();
                $("#login").val(data.login);
                $("#fio").val(data.fio);
                for (var n = 0;n< data.roles.length; n++) {
                    $("#roles").prepend("<option>" + data.roles[n] + "</option>");
                }

                $('#DetailUser').dialog({
                    height: 150,
                    width: 350,

                });
            }
        }
           )
    }
</script>
<div style="display:none" id="DetailUser">
    <table>
        <tr>
            <td>Логин</td>
            <td><input id="login"/></td>
           
        </tr>
        <tr>
            <td>ФИО</td>
             <td> <input id="fio" /></td>
        </tr>
        <tr>
            <td>Роли</td>
          <td>  <select id="roles"></select> </td>
        </tr>
    </table>
</div>

tp/Views/Shared/_Find.cshtml
@using tp.ServiceReference1
@using tp.Controllers
@using tp.special;
@model tp.Models.findObject

@{
    string mass = "";
    if (Model.shem_sostoinii!=null)
    {
     mass = "{ ";

    foreach (shemsost sch in Model.shem_sostoinii)
    {
        mass += "  " + sch.key.Replace(" ", "") + ": [ '" + sch.value[0] + "' ";
        for (int n = 1; n < sch.value.Count; n++)
        {
            mass += ",'" + sch.value[n] + "'";
        }
        mass += " ],";

    }
    mass = mass.Substring(0, mass.Length - 1) + "}";
    }
}

<script> 
    function settime(idelem, value) {
        $("#"+idelem).datepicker({
            dateFormat: 'dd.mm.yy'
        });
        $("#"+idelem).datepicker("setDate", value);
    }
</script>

             <button id='animfind'>Показать/Скрыть</button> 
<div id='find' style="display:none">
                  <form action='@ViewData["way"]' method='post' >   <input type='hidden' name='action' value='@ViewData["action"]'/> 
                      <table style=' border: 1px solid;  border-radius: 10px; margin-left: 3px'>
 @if (ViewData["issostoinie"] == null)
                            {
            <tr>
             @if (Model.param.sost_value != null)
             {
                  <td> <input name='sost' type='checkbox' checked  /> По состоянию </td>
            
             }
             else
             {
                     <td> <input name='sost' type='checkbox'   /> По состоянию </td>
         
                 
             }
                <td><select name="sost_value" id="sost_value"></select></td>
                 </tr>
 }
                           @if (ViewData["iskategorii"] == null)
                            {
                           <tr>
                    @if (Model.param.kategorii_value != null)
                    {
                  <td> <input name='kategorii' type='checkbox' checked  /> По категории </td>
          
                    }
                    else
                    {
                     <td> <input name='kategorii' type='checkbox'   /> По категории </td>
              
                    }
                      <td>@Html.listuser(Model.kategorii, Model.param.kategorii_value, "kategorii_value") </td>
               </tr>
                           }
                           @if (ViewData["isstate"] == null)
                            {
                 <tr>
                    @if (Model.param.state_value != null)
                    {
                  <td> <input name='state' type='checkbox' checked  /> По статусу </td>
          
                    }
                    else
                    {
                     <td> <input name='state' type='checkbox'   /> По статусу </td>
              
                    }
                      <td>@Html.listuser(Model.states, Model.param.state_value, "state_value") </td>
               </tr>
                           }
                           @if (ViewData["isschems"] == null)
                            {
                 <tr>
                    @if (Model.param.schem_value != null)
                    {
                  <td> <input name='schem' type='checkbox' checked  /> По схеме </td>
            
                    }
                    else
                    {
                     <td> <input name='schem' type='checkbox'   /> По схеме </td>
               
                    }
                      <td>@Html.listuser(Model.schems, Model.param.schem_value, "schem_value") </td>
                   
          </tr>
                           }
                            @if (ViewData["isusers"] == null)
                            {
                          <tr>
                           @if (Model.param.user_value != null)
                           {
                  <td> <input name='users' type='checkbox' checked  /> По пользователям </td>
            
                           }
                           else
                           {
                     <td> <input name='users' type='checkbox'   /> По пользователям </td>
               
                           }
                      <td> @Html.listuser(Model.users, Model.param.user_value, "user_value") </td>
          </tr>
                            }

                           @if (ViewData["isusersend"] == null)
                            {
                          <tr>
                           @if (Model.param.user_end != null)
                           {
                  <td> <input name='usersend' type='checkbox' checked  /> По последнему пользователю </td>
            
                           }
                           else
                           {
                     <td> <input name='usersend' type='checkbox'   /> По последнему пользователю </td>
               
                           }
                      <td> @Html.listuser(Model.users, Model.param.user_end, "userend_value") </td>
          </tr>
                            }


                           @if (ViewData["isdate"] == null)
                            {
 <tr>
     
@if (Model.param.begin != DateTime.MinValue)
{
    <td> <input name='isdate' type='checkbox' checked  /> По Дате создания </td>
    
   
    
    <script>
        $(document).ready(function () {
            settime('begin', '@Model.param.begin.Date.ToString("dd/MM/yy")');
            settime('end', '@Model.param.end.Date.ToString("dd/MM/yy")');
        }
        )
    </script>
}
else
{
     <td> <input name='isdate' type='checkbox'   /> По Дате создания </td>
      <script>
          $(document).ready(function () {
              settime('begin', '');
            settime('end', '');
        }
        )
    </script>
}
     <td> От <input type="text" name="begin" id="begin"  /> До <input type="text" name="end" id="end"  /> </td>
   </tr>
                           }







  @if (ViewData["iscontrol"] != null)
  {
<tr>
  
    <td colspan="2">
        @if (Model.param.iscontrol == true)
        {
        <input type="checkbox"   name="iscontrol" checked />
        }
        else
        {
            <input type="checkbox"  name="iscontrol"  />  
        }
   Под контролем </td>
</tr>
  }
              <tr> 
                  <td colspan='2' style='text-align: center'> <button type='submit'>Поиск</button> 

                  </td>

              </tr> 

                      </table> <br /> 

                  </form> 

</div>
@if (mass!="")
{
       <script>
           var mass = @( Html.Raw(mass))
           function setnewsostoinii(list,value) {
               var $el = $("#sost_value");
               $el.empty();
               for (var n = 0; n < list.length; n++) {

                   if (list[n]==value)
                       $el.append("<option selected='selected'>" + list[n] + "</option>");
                   else
                       $el.append("<option >" + list[n] + "</option>");
               }
           }
           $(document).ready(function () {
              
        
               setnewsostoinii(mass[$("#schem_value option:selected").text().replace(/\s+/g, '')], '@(Model.param.sost_value)');

                   $("#schem_value").change(function () {

                       setnewsostoinii(mass[$("#schem_value option:selected").text().replace(/\s+/g, '')], mass[$("#schem_value option:selected").text().replace(/\s+/g, '')][0]);
                   });
               })

        
    
</script>
}

tp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  
    <meta charset="Windows-1251" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
      @Styles.Render("~/Content/jquery.toastmessage-min.css")
    @Scripts.Render("~/Scripts/jquery-1.8.2.js")
         @Scripts.Render("~/Scripts/jquery.signalR-1.1.3.min.js")
@Scripts.Render("~/SignalR/Hubs")
  @Scripts.Render("~/Scripts/events.js")
@Scripts.Render("~/Scripts/notification.js")
   @Scripts.Render("~/Scripts/jquery.toastmessage-min.js")
@Scripts.Render("~/Scripts/all.js")


     @Styles.Render("~/Content/jquery-ui.css") 
<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
</head>
<body>
    
    <script type="text/javascript">
        var currenturl = '@Url.Action("", "Utils/notification.svc")'
        
        var Parenturl = '@Url.Action("", "")';

        var hnotification = new notification();
        hnotification.addEvent(function (h) {
            var count = $("#notificationcount").text();
            count++;
            $("#notificationcount").text(count);
            var textshow;
            switch (h.type) {
                case "status":
                    textshow = "Изменен статус";
                    break;
                case "sendtouser":
                    textshow = "ТП отослан пользователю";
                    break;
                case "sendedtouser":
                    textshow = "Пользователь принял ТП";
                    break;
            }
            var hrefdetail='@Url.Action("detail", "Detail")'
            $().toastmessage('showToast', {
                text: '<p style="font:bold italic 110% serif;margin-left:0;">' + textshow + '</p>'+ '<p style="margin-left:0;"><a style="font:bold italic 150% serif;" href="' + hrefdetail + '?number=' + h.z_id + '">Открыть ТП</a></p>',
                sticky: true,
                position: 'top-right',
                type: 'success',
                closeText: '',
                close: function () {
                    console.log("toast is closed ...");
                }
            });
        }
        );
    </script>
 @{
     Html.RenderPartial("_DetailUser");

 }


        
    <div id="login_div">
        <div style="float:left;  padding:.6em; font-size:1.5em;">
Технологические процессы

        </div>
        <div style="margin:0.6em;padding:0.6em;background-color:#555;float:right;">
        <ul>
            @{
                string user = tp.special.Auth.get_user().login;
                List<tp.ServiceReference1.Notification_to_user> list;
                tp.ServiceReference1.PublisherServiceClient client = tp.special.Auth.get_client();
                client.get_Notifications_user(tp.special.Auth.get_user(), out list);
            bool isboss=    client.isboss(user);
             
            }
   
       @if (isboss == true)
       {
           <li > @Html.ActionLink("Уведомления","Index","Notification") (<a id="notificationcount">@list.Where(n=>n.isnew==true).ToList().Count.ToString()</a>)</li>
       }
       <li>Добро пожаловать:@user      @Html.ActionLink("Выйти", "Logoff", "Auth")</li>
   
          
   
                </ul>
            </div>
            </div>
        
   
    
       <ul class="solidblockmenu1">
            <li>
                @Html.ActionLink("Технические процессы", "Index", "Home")
            </li>
          @if (isboss)
          {
<li>@Html.ActionLink("Контроль","control","Home")</li>
              <li>@Html.ActionLink("История ТП","Index","HistoryZaivok")</li>
          }
      <li>@Html.ActionLink("Статистика","Index","Statistic")</li>      
        </ul>

    @RenderBody()

  
  
</body>
</html>

tp/Views/Shared/_integro.cshtml
@{
    bool script = Convert.ToBoolean( ViewData["script"]);
    Dictionary<string,string> list;
 
        list = ViewData["ClassSelector"] as Dictionary<string,string>;
        string value = ViewData["value"].ToString();
        List<string> actions = (List<string>)ViewData["actions"]; 
        string idinput = ViewData["idinput"].ToString();
        string classselector = idinput + "ClassSelector";
        string display = ViewData["displayvalue"].ToString();
        string isvisible = ViewData["visibleClass"].ToString();
        string servername = "/"+ViewData["servername"].ToString()+"/inmeta/";
        string ajaxcallbackController = ViewData["ajaxcallbackController"].ToString();
         string ajaxcallbackAction = ViewData["ajaxcallbackAction"].ToString();
      display=  display.Replace("\"", "").Replace(@"\", "");
        
}
@if (script==true)
{
    <script type="text/javascript">
        function sendajax(txt) {
            $.ajax({
                type: "Post",
                url:"@Url.Action(ajaxcallbackAction,ajaxcallbackController)"+"?key="+encodeURIComponent('@(idinput)')+"&txt=" + encodeURIComponent(txt), success: function (result) {

                    location.reload();

                }
            }
            );
        }
    </script>
<script type="text/javascript" language="javascript">document.bgColor = '#EEEEEE';</script><script language="VBScript">
option explicit
const INMETA_PATH ="@servername"
sub DataObjectBoxAction(byval controlId, byval action)
dim className, objectId, selector, objectRef, result

set selector = document.all(controlId+ "ClassSelector")
set objectRef = Form1(controlId)
if (Len(objectRef.value) > 0) then
	objectId = Left(objectRef.value, 12)
	className = Right(objectRef.value, Len(objectRef.value) - 13)
end if
select case action
	case "clear"
		objectRef.value = ""
     sendajax("")
	
	case "select"
		result = ShowModalDialog(INMETA_PATH & "object_list_form.asp?class=" & selector.value, _
			"modal", "center:yes; help:no; resizable:yes; status:yes; dialogWidth:800px; dialogHeight: 600px;")
	case "create"
		if (className = selector.value) and (Len(objectId) > 0) then
			result = ShowModalDialog(INMETA_PATH & "object_data_form.asp?class=" & className & "&id=" & objectId, _
				"modal", "dialogWidth:800px; dialogHeight: 600px; center:yes; help:no; resizable:yes; status:no")
		else
			result = ShowModalDialog(INMETA_PATH & "object_data_form.asp?class=" & selector.value, _
				"modal", "dialogWidth:800px; dialogHeight: 600px; center:yes; help:no; resizable:yes; status:no")
		end if
end select
if not IsEmpty(result) and not IsNull(result)  then
	
     sendajax(result & ":" & selector.value)
end if
   
end sub
</script>
}
  
<div>
 
	<input type="hidden" name="@(idinput)" id="@(idinput)" value="@(value)" />
    <select name='@classselector' style="display:@isvisible">
            @foreach (KeyValuePair<string,string> s in list)
    {
    
                <option value='@s.Key'>
								@s.Value
							</option>
    }
							

<input  value="@(display)" />
</div>

@if(actions==null)
{
if (value != "")
{
    <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'create');" style="cursor:hand;color:blue;">Редактировать</span>

}
 <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'select');" style="cursor:hand;color:blue;">Выбрать</span>  
if (value != "")
{
     <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'clear');" style="cursor:hand;color:blue;">Очистить</span>
     
     }
  }
else
{
    if (!actions.Exists(m => m == "Выбрать"))
    {
        <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'select');" style="cursor:hand;color:blue;">Выбрать</span>
    }
    if ((!actions.Exists(m => m == "Редактировать")) && (value != ""))
    {

        <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'create');" style="cursor:hand;color:blue;">Редактировать</span>

    }
    if ((!actions.Exists(m => m == "Создать")) && (value == ""))
    {
        
        <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'create');" style="cursor:hand;color:blue;">Создать</span>
    }
    if ((!actions.Exists(m => m == "Очистить")) && (value != ""))
    {
 
        <span onclick="javascript:DataObjectBoxAction('@(idinput)', 'clear');" style="cursor:hand;color:blue;">Очистить</span>

    }
}  

 


tp/Views/Shared/_list.cshtml
<script>


    function commitchanges() {


        

            $("#"+@(ViewData["name"])+"pole").text(this.value);
     

    }

  

</script>

tp/Views/Shared/userError.cshtml
@{
    Layout = null;
    string text = ViewData["error_text"].ToString();
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Error</title>
</head>
<body>
    <hgroup>
        <h1>Error.</h1>
        <h2> @text</h2>
        
    </hgroup>
   @Html.ActionLink("На главную", "Index", "Home")
    @Html.ActionLink("Выйти", "Logoff", "Auth")
</body>
</html>